import React, { useState } from 'react'
import Head from 'next/head';
import AppNavbar from '../../components/AppNavbar'
import useStateContext from '../../context/ContextProvider';
import CreateEvent from '../../components/createEvent/CreateEvent';
import ScheduleAvailability from '../../components/availability/ScheduleAvailability';
import HotelScheduleAvailability from '../../components/availability/HotelScheduleAvailability';
import SoccerScheduleAvailability from '../../components/availability/SoccerScheduleAvailability';
import BarberScheduleAvailability from '../../components/availability/BarberScheduleAvailability';


const id = () => {
    const { anchorEl, openTimeZonePopover, closeTimeZonePopover } = useStateContext();
    return (
        <div className='w-screen h-screen' >
            <Head>
                <title>{`Working Hours - Edit ${"One-on-One Event Type"} - Turpio`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <AppNavbar
                pageTitle={`Edit ${"One-on-One Event Type"}`}
                disableSecondControl={true}
                backBtn={true}
                backBtnNavigate="/home"
            />
            <CreateEvent  />
            <ScheduleAvailability />
            

        </div>
    )
}

export default id